### ISSUE TITLE
Request failed, Response code: -1; Request ID: null... improve error handling

### ISSUE THREAD

**Issue by yizhixiaotaozi** [huaweicloud/huaweicloud-sdk-java-obs#115]
INFO  c.o.s.internal.RestStorageService - OkHttp cost 5 ms to apply http request
WARN  c.o.s.internal.RestStorageService - Request failed, Response code: -1; Request ID: null; Request path: https://xxx.obs.cn-south-1.myhuaweicloud.com/xxx.pdf
ERROR com.obs.services.AbstractClient - Storage|1|HTTP+XML|putObject||||2023-01-11 20:31:04|2023-01-11 20:31:04|||-1|
 com.obs.log.AccessLogger - 2023-01-11 20:31:04 484|com.obs.services.internal.RestStorageService|executeRequest|589|OkHttp cost 5 ms to apply http request
2023-01-11 20:31:04 484|com.obs.services.internal.RestStorageService|handleThrowable|217|Request failed, Response code: -1; Request ID: null; Request path: https://xxx.obs.cn-south-1.myhuaweicloud.com/xxx.pdf
2023-01-11 20:31:04 484|com.obs.services.AbstractClient|doActionWithResult|412|Storage|1|HTTP+XML|putObject||||2023-01-11 20:31:04|2023-01-11 20:31:04|||-1|
20:31:04.484 [20191204145826$pis$ukGrabOrderLabelTaskDealMulti-265842-exe-0] ERROR c.w.f.s.s.obs.FmsObsStorageClient - Upload failed, object key: 2023/01/11/xxx.pdf 

上面是报错，我通过代码看到是com.obs.services.internal.RestStorageService 217行报的。 3.21.12的包。

…… 这个报错，结合源码，根本看不出错误的原因。功能本来没啥问题，23年1月11号 晚上20点突然一大堆这样的错误。这咋排查。
优化一下报错信息吧，别给-1

**Comment by liaofuda** [comment]
您好，感谢使用obs sdk，报错-1是客户端报错，可以把堆栈打出来看一下，另外报错-1的优化，内部已经提了需求，正在做的。

**Comment by scp-anyone** [comment]
所以问题出在哪里，怎么解决啊
