### ISSUE TITLE
ObsClient.setFile()数据流不关闭的问题

### ISSUE THREAD

**Issue by Anricx** [huaweicloud/huaweicloud-sdk-java-obs#2]
根据`com.obs.services.internal.transPutObjectRequest`代码中的逻辑在设置文件的时候，这里方法会
```java
	input = new FileInputStream(request.getFile());
```
得到文件流, 但是后面没有关闭这个文件流的逻辑。
所以导致了文件上传后文件依然被进程占用。

**Comment by yangqican** [comment]
> 根据`com.obs.services.internal.transPutObjectRequest`代码中的逻辑在设置文件的时候，这里方法会
> 
> ```java
> 	input = new FileInputStream(request.getFile());
> ```
> 
> 得到文件流, 但是后面没有关闭这个文件流的逻辑。
> 所以导致了文件上传后文件依然被进程占用。

在调用该接口的地方已使用finally对文件流进行关闭

**Comment by Anricx** [comment]
fixed?
