### ISSUE TITLE
threw exception; nested exception is java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by dwhgygzt** [huaweicloud/huaweicloud-sdk-java-obs#20]
sdk version is 3.19.7

Maven mvnrepository last version also is    3.19.7

**Comment by goodcode-best** [comment]
能麻烦提供一下详细的堆栈吗？

**Comment by goodcode-best** [comment]
> sdk version is 3.19.7
> 
> Maven mvnrepository last version also is 3.19.7

能麻烦提供一下详细的堆栈吗？

**Comment by dwhgygzt** [comment]
升级 3.20.3 以上 就好了

**Comment by airxiechao** [comment]
3.20.4.2的obs依赖了okhttp3.14.2，和项目的4.x的okhttp版本不兼容
