### ISSUE TITLE
Maven Central 上的 SDK 版本过低 SDK released on Maven Central is outdated

### ISSUE THREAD

**Issue by DingXiangbing** [huaweicloud/huaweicloud-sdk-java-obs#21]
你好。OBS SDK 在本站的最新版本是 3.20.4（发布于 5 月 6 日），而在 Maven 中央仓库上的最新版本是 3.19.7 （发布于去年 8 月 2 日）。希望能够同步更新。
Hello there, the SDK released on Maven Central is outdated (3.19.7, released on 2nd August, last year) compared to the one released on Github (3.20.4, released on 6th May). Could you please keep it updated.

**Comment by goodcode-best** [comment]
> 你好。OBS SDK 在本站的最新版本是 3.20.4（发布于 5 月 6 日），而在 Maven 中央仓库上的最新版本是 3.19.7 （发布于去年 8 月 2 日）。希望能够同步更新。
> Hello there, the SDK released on Maven Central is outdated (3.19.7, released on 2nd August, last year) compared to the one released on Github (3.20.4, released on 6th May). Could you please keep it updated.

感谢你的反馈，尽快同步一下

**Comment by goodcode-best** [comment]
> 你好。OBS SDK 在本站的最新版本是 3.20.4（发布于 5 月 6 日），而在 Maven 中央仓库上的最新版本是 3.19.7 （发布于去年 8 月 2 日）。希望能够同步更新。
> Hello there, the SDK released on Maven Central is outdated (3.19.7, released on 2nd August, last year) compared to the one released on Github (3.20.4, released on 6th May). Could you please keep it updated.

已经发布了

**Comment by DingXiangbing** [comment]
你好。项目在升级到 3.20.4(.1) 后编译失败。检查后发现 Jar 包内未包含 class 文件。
Hello. Our project failed to compile after OBS SDK upgraded to either 3.20.4 or 3.20.4.1. Examining the jar file, we found that classes were not packed together.
