### ISSUE TITLE
ObsClient#putObject(bucketName, objectKey, file)  NullPointerException

### ISSUE THREAD

**Issue by sannmizu** [huaweicloud/huaweicloud-sdk-java-obs#23]
异常定位到com.obs.services.internal.RequestConvertor 467行，request.getFile()为null。发现就在上面462行的的request.setInput将file置为null了，导致了空指针异常。

**Comment by goodcode-best** [comment]
你好，问题已修复，请获取最新版本3.20.6.1

**Comment by sannmizu** [comment]
> 你好，问题已修复，请获取最新版本3.20.6.1

好的，辛苦了

**Comment by changsteven** [comment]
唉，这种错误都有。。。好坑啊
