### ISSUE TITLE
文件名中带有中文的文件上传后，生成的URL无法正确的访问到文件

### ISSUE THREAD

**Issue by naihewuxiao** [huaweicloud/huaweicloud-sdk-java-obs#24]

**Comment by goodcode-best** [comment]
麻烦更详细的描述一下你的问题呢？

**Comment by naihewuxiao** [comment]
代码：

 @Resource
    private ObsClient obsClient;

public String putObject(String bucketName,String objectName, InputStream inputStream) {
        try {
            PutObjectResult result = obsClient.putObject(bucketName, objectName, inputStream);
            log.info("Obs putObject inputStream result:" + result);
            return result.getObjectUrl();
        } catch (ObsException e) {
            throw new RuntimeException("Obs putObject inputStream error", e);
        }
    }

问题出处：
PutObjectResult result = obsClient.putObject(bucketName, objectName, inputStream);
如果objectName中含有中文，上传obs成功，但是返回的url中的文件名是乱码的，无法通过返回的url访问到上传的对象

查看华为云OBS中对应文件，也是中文名

**Comment by goodcode-best** [comment]
你好，url中的中文，都是要经过url编码的，你说的乱码不是乱码，是经过url编码后的

**Comment by naihewuxiao** [comment]
嗯嗯，好的，但是经过编码后返回的url无法访问到obs中对应的文件，请问这个怎么解决呢？

**Comment by goodcode-best** [comment]
你好，抱歉未能解决你的困惑，能否麻烦你将过程更详细的描述一下呢，比如将你所遇到的问题的前后的url提供一下。我当前还不是很清楚你说说的“无法访问”具体是什么现象？

**Comment by naihewuxiao** [comment]
问题已经找到了
这是上传文件的时候返回的url：https://tc-bucket.obs.cn-east-3.myhuaweicloud.com:443/%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6.xlsx

然后因为需要生成临时url,此时我取最后一个斜杠后面的字段作为文件名传入生成临时url的方法，此时传入文件名为：%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6.xlsx
导致再一次编码，最后返回的临时url为
https://tc-bucket.obs.cn-east-3.myhuaweicloud.com:443/%25E4%25B8%25AD%25E6%2596%2587%25E6%2596%2587%25E4%25BB%25B6%25E5%2590%258D%25E6%25B5%258B%25E8%25AF%2595%25E6%2596%2587%25E4%25BB%25B6.xlsx?AccessKeyId=CYJSSRJCD6DIQ8EXOBVL&Expires=1599548978&Signature=4cwn8mf6ghfLbnUXb4i5TSU3kYg%3D
，文件名被编码了2次，导致临时url无法访问到文件

**Comment by goodcode-best** [comment]
好的，建议你计算临时url的时候，直接取objectKey进行计算。

**Comment by goodcode-best** [comment]
如果没有其他问题，我们先关闭该issues了。
