### ISSUE TITLE
不能上传文件到桶内的文件夹里？

### ISSUE THREAD

**Issue by xin10355** [huaweicloud/huaweicloud-sdk-java-obs#25]

**Comment by goodcode-best** [comment]
麻烦更详细的描述下你的问题呢？

**Comment by goodcode-best** [comment]
如果没有疑问，我就先关闭该issues了？

**Comment by xin10355** [comment]
sry叨扰了,我明白了,但是可不可以把"上传文件"的文档中的代码示例，改成"创建文件夹"中的代码示例呢，当时看"上传文件"的文档中的代码示例的时候，没有搞清楚objectKey的具体用法，哈哈
![image](https://user-images.githubusercontent.com/36719843/95149791-6339ab00-07b9-11eb-91ad-131140de5ad6.png)
