### ISSUE TITLE
putObject不支持自定义属性“origin”

### ISSUE THREAD

**Issue by yyyyxf** [huaweicloud/huaweicloud-sdk-java-obs#26]
putObject(String bucketName, String objectKey, InputStream input, ObjectMetadata metadata)

metadata包含属性“origin”，object上传后其它属性正常，但“origin”属性没有了

**Comment by goodcode-best** [comment]
在调用putObject前，尝试调用obsClient.setCanUseStandardHTTPHeaders(true); 开启允许设置自定义头域的开关。

**Comment by goodcode-best** [comment]
这个开关设置的是一个线程变量，一个线程只需要设置一次即可。
