### ISSUE TITLE
OBS servcie Error Message. java.lang.NoSuchMethodException: <init> [interface org.xml.sax.XMLReader]

### ISSUE THREAD

**Issue by zhangshexin** [huaweicloud/huaweicloud-sdk-java-obs#27]
使用官方的断点续传示例，报这个错误

代码如下：
`UploadFileRequest request = new UploadFileRequest("anne-bqj-file", objectname + "/" + fileMD5 + "." + endName);
            // 设置待上传的本地文件，其中localfile为待上传的本地文件路径，需要指定到具体的文件名
            request.setUploadFile(filePath);
            // 设置分段上传时的最大并发数
            request.setTaskNum(5);
            // 设置分段大小为10MB
            request.setPartSize(10 * 1024 * 1024);
            // 开启断点续传模式
            request.setEnableCheckpoint(true);

            request.setProgressListener(new ProgressListener() {

                @Override
                public void progressChanged(ProgressStatus status) {
                    mObsUploadCallBack.progressChange(status);
                }
            });
            // 每上传1MB数据反馈上传进度
            request.setProgressInterval(1024 * 1024L);

            try{
                // 进行断点续传上传
                CompleteMultipartUploadResult result = obsClient.uploadFile(request);
                LogUtils.e("上传成功",result.getStatusCode() + "");
                if (result.getStatusCode() == 200){
                    
                }else{
                   
                }
            }catch (ObsException e) {
                // 发生异常时可再次调用断点续传上传接口进行重新上传
                LogUtils.e("上传失败，重新断点上传");
                e.printStackTrace();
//                obsClient.uploadFile(request); 不继续尝试，直接失败，让用户自己处理
            }`

**Comment by goodcode-best** [comment]
麻烦检查一下rt.jar包是否已引入到classpath。
