### ISSUE TITLE
Duplicate classes in dependencies

### ISSUE THREAD

**Issue by WongYH01** [huaweicloud/huaweicloud-sdk-java-obs#28]
As per following the documentation, i have added the dependencies into the gradle build
![image](https://user-images.githubusercontent.com/65993170/96005203-cfc64100-0e6e-11eb-8e49-986501a8ccfb.png)

However, when I sync the gradle build, it shows this error:
![image](https://user-images.githubusercontent.com/65993170/96005148-c1782500-0e6e-11eb-9bcf-5c0ed7c5449b.png)

I am using version 3.20.1(Latest version) of OBS Android SDK and using android studio referencing the Android SDK developer guide to try and do it

**Comment by goodcode-best** [comment]
Hi, try version 3.20.3.    http://mirrors.huaweicloud.com/repository/maven/huaweicloudsdk/com/huawei/storage/esdk-obs-android/3.20.3/

**Comment by WongYH01** [comment]
Found a good link that removes some dependencies while not affecting what its supposed to do:
https://medium.com/@diewland/huawei-cloud-installing-object-storage-obs-sdk-for-android-4-4-8aec99588dc9
