### ISSUE TITLE
 File-Based Upload Error

### ISSUE THREAD

**Issue by furkanozbay** [huaweicloud/huaweicloud-sdk-java-obs#29]
Performing file based upload (described in here: https://support.huaweicloud.com/en-us/sdk-java-devg-obs/obs_21_0603.html) gives error.

Version: 3.20.6

In ````RequestConvertor```` class
````java 
long fileSize = request.getFile().length();
````
this line raised error because of method call, ````length()````, on null object: ````request.getFile()````

This is caused from this line
````java
request.setInput(new FileInputStream(request.getFile()));
````
 When you set input to request it sets file to null. This is the setInput method in ````PutObjectRequest```` class
````java
    public void setInput(InputStream input) {
        this.input = input;
        this.file = null;
    }
````

**Comment by goodcode-best** [comment]
Thanks for your suggestion, this place is indeed a problem and has been fixed in 3.20.6.1:https://mvnrepository.com/artifact/com.huaweicloud/esdk-obs-java/3.20.6.1
