### ISSUE TITLE
Dragonwell 11环境下无法找到sun.misc.BASE64Decoder

### ISSUE THREAD

**Issue by BruceAn1978** [huaweicloud/huaweicloud-sdk-java-obs#33]
调用ObsClient.createTemporarySignature()方法生成临时访问url，会报下面的告警日志，但是临时url正常生成了。

> WARN  class not found exception. com.obs.services.internal.utils.ReflectUtils 
> java.lang.ClassNotFoundException: sun.misc.BASE64Decoder
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:315)
> 	at com.obs.services.internal.utils.ReflectUtils.<clinit>(ReflectUtils.java:79)
> 	at com.obs.services.internal.utils.ServiceUtils.toBase64(ServiceUtils.java:407)
> 	at com.obs.services.internal.utils.ServiceUtils.signWithHmacSha1(ServiceUtils.java:184)
> 	at com.obs.services.internal.ObsService.createTemporarySignatureResponse(ObsService.java:1023)
> 	at com.obs.services.ObsClient.createTemporarySignature(ObsClient.java:528)

**Comment by BruceAn1978** [comment]
是不是需要替换sun.misc.BASE64Decoder引用为java.util.Base64了？！

**Comment by BruceAn1978** [comment]
反应这么慢吗？不是华为的作风啊！！！

有人能给个回复不？解决方案我都给出来了。

**Comment by lichangyuan1993** [comment]
@BruceAn1978 
有的用户还在用jdk6、7，Base64在Jdk 8加入。实际ReflectUtils已经反射了java.util.Base64，至于报错，只是检查型异常，不会导致业务执行中断。

以下代码来自`com.obs.services.internal.utils.ReflectUtils`

`    static {
        try {
            androidBase64Class = Class.forName("android.util.Base64");
        } catch (ClassNotFoundException var9) {
        }

        try {
            Class<?> base64 = Class.forName("java.util.Base64");
            jdkNewEncoder = base64.getMethod("getEncoder").invoke((Object)null);
            jdkNewDecoder = base64.getMethod("getDecoder").invoke((Object)null);
        } catch (ClassNotFoundException var3) {
            ILOG.warn("class not found exception.", var3);
        } catch (IllegalAccessException var4) {
            ILOG.warn("illegal access exception.", var4);
        } catch (IllegalArgumentException var5) {
            ILOG.warn("illegal argument exception.", var5);
        } catch (InvocationTargetException var6) {
            ILOG.warn("invocation target exception.", var6);
        } catch (NoSuchMethodException var7) {
            ILOG.warn("nosuch method exception.", var7);
        } catch (SecurityException var8) {
            ILOG.warn("security exception.", var8);
        }

        try {
            jdkBase64EncoderClass = Class.forName("sun.misc.BASE64Encoder");
        } catch (ClassNotFoundException var2) {
            ILOG.warn("class not found exception.", var2);
        }

        try {
            jdkBase64DecoderClass = Class.forName("sun.misc.BASE64Decoder");
        } catch (ClassNotFoundException var1) {
            ILOG.warn("class not found exception.", var1);
        }

    }`

**Comment by BruceAn1978** [comment]
既然是类型检查，可以把错误堆栈详情不要打印出来，只是打印一行警告日志即可。
现在每调用一次就会打印一堆错误堆栈，其实功能到没有影响。

**Comment by willWang8023** [comment]
楼主怎么解啊，需要处理吗？有么有华为的人出来给个解决方案啊，看着难受
