### ISSUE TITLE
com.obs.services.exception.ObsException: OBS servcie Error Message. Request Error: javax.net.ssl.SSLException: Write error: ssl=0x84abb2c8: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by victoryGithup** [huaweicloud/huaweicloud-sdk-java-obs#34]
vivoY66 手机  安卓系统：5.0 使用obg 上传文件服务（上传视频文件，请官方人员给出原因谢谢）。查看SDK文档及论坛没有给出合理解决办法 出现   如下错误：
com.obs.services.exception.ObsException: OBS servcie Error Message. Request Error: javax.net.ssl.SSLException: Write error: ssl=0x84abb2c8: I/O error during system call, Connection reset by peer
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:727)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:2537)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.putObject(ObsClient.java:1625)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.putObject(ObsClient.java:1656)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.putObject(ObsClient.java:1642)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.gaga.live.video.VideoPreviewActivity.lambda$hwOBSPut$10(VideoPreviewActivity.java:323)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at com.gaga.live.video.-$$Lambda$VideoPreviewActivity$vkfMqIFZv_TK88PL6bMM1QKo3hg.subscribe(lambda)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-26 09:47:35.477 30746-30746/com.gaga.live W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err: Caused by: javax.net.ssl.SSLException: Write error: ssl=0x84abb2c8: I/O error during system call, Connection reset by peer
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@204516017@20.45.16 (040306-344294571):3)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@204516017@20.45.16 (040306-344294571):5)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.Okio$1.write(Okio.java:79)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:42)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.ForwardingSink.write(ForwardingSink.java:35)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:92)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.RepeatableRequestEntity.writeToBIO(RepeatableRequestEntity.java:110)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.RepeatableRequestEntity.writeTo(RepeatableRequestEntity.java:131)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at okhttp3.RealCall.execute(RealCall.java:92)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:483)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.RestStorageService.performRestPut(RestStorageService.java:807)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.RestStorageService.performRestPut(RestStorageService.java:798)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.internal.ObsService.putObjectImpl(ObsService.java:2045)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.access$5800(ObsClient.java:159)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient$45.action(ObsClient.java:1632)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient$45.action(ObsClient.java:1626)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:     at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:2525)
12-26 09:47:35.487 30746-30746/com.gaga.live W/System.err:  ... 19 more

**Comment by mpb159753** [comment]
看起来是跟服务端进行 SSL 加密协商是时候挂掉了，检查下网络和证书。

**Comment by SuperBeagleDog** [comment]
我这边有一台魅族机也遇到这个问题，原因是wifi设置了抓包的代理证书，
但在我手动删除代理证书后，还是不行，关掉代理也不行，仍然会报这个错，
最后直接恢复出厂设置就OK了。可以确定是配置了代理相关，导致网络请求出了问题。

**Comment by victoryGithup** [comment]
HI 。 。 。 。 。 。 
 您 的 信 件 我 已 经 收 到了哦！感谢您的来信。祝您生活愉快 ！
