### ISSUE TITLE
元数据包含中文标点符号时, 会报错.

### ISSUE THREAD

**Issue by lian88jian** [huaweicloud/huaweicloud-sdk-java-obs#35]
RestUtils里的中文表达式只能匹配中文字, 不能匹配中文标点符号. 导致报错

**Comment by mpb159753** [comment]
HTTP 编码规范规定了不允许发送非 ascii 码字符，之前的版本帮助用户做了部分编码，但是还是建议用户来自己做编解码，毕竟用户自己更清楚当前业务是否需要编解码。
