### ISSUE TITLE
关于android 对象存储服务OBS 使用时发现对“ResumableClient$UploadCheckPoint”检验代码抛出异常而无法正确的续传，应该怎么处理？

### ISSUE THREAD

**Issue by Rany-k** [huaweicloud/huaweicloud-sdk-java-obs#44]
我在使用 对象存储服务 OBS > SDK参考> Android> 上传对象> 断点续传上传 的时候，百分百按照该文档所描述的Demo进行操作，发现并不能实现续传功能，在翻阅源码发现，在解析uploadFile_record文件时，所使用的SecureObjectInputStream类中，对“ResumableClient$DownloadCheckPoint”和“ResumableClient$UploadCheckPoint”进行了解析验证，这里的解析代码 String name = desc.getName();中还被得到name 为UploadCheckPoint内部所使用的类，例如“java.util.ArrayList”“UploadPart”等的结果，造成uploadFile_record文件解析过程抛出异常，而造成文件必须重新开始上传。请问是不支持断点续传了吗？还是应该如何正确实现断点续传？

public final class SecureObjectInputStream extends ObjectInputStream {
    public SecureObjectInputStream() throws IOException, SecurityException {
    }

    public SecureObjectInputStream(InputStream in) throws IOException {
        super(in);
    }

    protected Class<?> resolveClass(ObjectStreamClass desc) throws IOException, ClassNotFoundException {
        String name = desc.getName();
        if (!name.equals("com.obs.services.internal.ResumableClient$DownloadCheckPoint") && !name.equals("com.obs.services.internal.ResumableClient$UploadCheckPoint")) {
            throw new ClassNotFoundException(name + "not find");
        } else {
            return super.resolveClass(desc);
        }
    }
}

**Comment by mpb159753** [comment]
请补充报错信息和版本号信息，另外 Android SDK 已发布新版本，也建议您尝试新版本是否可以使用
