### ISSUE TITLE
没有查询指定bucket是否存在的接口

### ISSUE THREAD

**Issue by wangjiaxi90** [huaweicloud/huaweicloud-sdk-java-obs#48]
目前的操作只能是把全部bucker全部查出来，然后循环遍历去判断有没有和我指定bucket名称相同的返回，感觉这样很浪费宽带和时间。

**Comment by mpb159753** [comment]
列举桶的请求会一次性返回所有桶信息，不需要多次访问，对网络的消耗并不大，您可以对返回结果进行遍历，获取需要的桶
