### ISSUE TITLE
临时访问signUrl 访问不了对象 Invalid date (should be seconds since epoch)

### ISSUE THREAD

**Issue by xiaoguolong** [huaweicloud/huaweicloud-sdk-java-obs#50]
![image](https://user-images.githubusercontent.com/33684988/127477900-fdb00d7f-7b8e-4b2c-b702-f5820379bd73.png)
![image](https://user-images.githubusercontent.com/33684988/127477988-1c4f62d7-4bde-40dd-ba5c-8c776d476d6d.png)
没有临时的url直接访问对象吗

**Comment by mpb159753** [comment]
报错有解释的，should be seconds since epoch，即这个时间应该是从当前到过期的秒数，如 3600 就是指一小时后过期

**Comment by xiaoguolong** [comment]
文档说临时链接最长只有7天，没有永久的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huaweicloud/huaweicloud-sdk-java-obs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月2日(星期一) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huaweicloud/huaweicloud-sdk-java-obs] 临时访问signUrl 访问不了对象 Invalid date (should be seconds since epoch) (#50)





 
报错有解释的，should be seconds since epoch，即这个时间应该是从当前到过期的秒数，如 3600 就是指一小时后过期

**Comment by mpb159753** [comment]
永久 AKSK 的话最长1年。只有公共读对象是永久的，其他都有期限
