### ISSUE TITLE
没有一个版本这个方法是好的

### ISSUE THREAD

**Issue by qich1234** [huaweicloud/huaweicloud-sdk-java-obs#55]
BucketStorageInfo storageInfo =obsClient.getBucketStorageInfo(“backetName”);
Long num=storageInfo.getObjectNumber();//对象个数
Long size=storageInfo.getSize();//空间大小

**Comment by qich1234** [comment]
访问报错，换了N个版本，均报错。
![image](https://user-images.githubusercontent.com/90487563/132932042-b49e0469-d846-4faa-8005-b505b7d0a7f9.png)
![image](https://user-images.githubusercontent.com/90487563/132932093-dfa6b27b-6b69-4ded-8f41-038e671b55d5.png)

**Comment by qich1234** [comment]
![image](https://user-images.githubusercontent.com/90487563/132932100-747d11c1-53a6-4561-9274-c83d45f49d2b.png)

**Comment by mpb159753** [comment]
详细报错发下看看呢？顺带把 debug 日志打开下，方便定位问题
