### ISSUE TITLE
打包提示log4j最低Android sdk需要到26

### ISSUE THREAD

**Issue by ChaoYongAtom** [huaweicloud/huaweicloud-sdk-java-obs#61]
不是说最低支持19吗？

**Comment by LiWeiQiangAndroid** [comment]
没个android demo吗

**Comment by mpb159753** [comment]
安卓版不用打包 log4j2 
可以直接引用 maven 的已打包好的 https://mvnrepository.com/artifact/com.huaweicloud/esdk-obs-android/3.21.11
