### ISSUE TITLE
列举对象，不能多个时间过滤吗

### ISSUE THREAD

**Issue by BetterFive** [huaweicloud/huaweicloud-sdk-java-obs#63]
marker 列举对象的起始位置，返回的对象列表将是对象名按照字典序排序后该参数以后的所有对象。
只有marker 这个有时候满足不了

**Comment by mpb159753** [comment]
抱歉这是由于对象存储的架构决定的，业界目前都只能通过 marker 来进行列举，可以参考这个方案来实现替代：https://bbs.huaweicloud.com/blogs/381055
