### ISSUE TITLE
Java SDK  ：obsClient.createBucket(bucketName) 报错 400

### ISSUE THREAD

**Issue by acChris** [huaweicloud/huaweicloud-sdk-java-obs#87]
> responseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>IllegalLocationConstraintException</Code><Message>The https://obs.cn-east-3.myhuaweicloud.com location constraint is incompatible for the region specific endpoint this request was sent to.</Message>

终端，ak 和 sk 都是对的。其他操作都可以，只有这个创建桶会报错。

**Comment by mpb159753** [comment]
创建桶时候填了 region，但是这个 region 又跟你用的 endpoint 不一致，尝试指定正确 region 就行
